version: '3.8'

services:
  mongo_db:
    container_name: database_container
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db
      

  node-app:
    build: .
    ports:
      - "3000:3000"
    environment:
      APP_NAME: "NodeJS REST API"
      PORT: 3000
      DB_URI: mongodb://mongo_db:27017/test
    depends_on:
      - mongo_db  

volumes:
  mongo_db: {}
